#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 900000

#undef RGB_MATRIX_VAL_STEP
#define RGB_MATRIX_VAL_STEP 24

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "VGQwX/pj7Q6E"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

